#!/usr/bin/env python3
"""
generate-icon.py -- emit a thermometer Finder icon family (Rez 'data' blocks at
resource ID -16455) for the CPU Temp Control Strip module. No image libraries:
the bitmap is drawn procedurally.

Produces ICN#/icl8 (32x32) and ics#/ics8 (16x16). ICN#/ics# carry the 1-bit
image + mask; icl8/ics8 carry 8-bit colour. The Finder composites the colour
icons through the '#' mask, so background pixels in the colour icons are ignored.

Codes in the drawing grid:
  0 = background (transparent)   1 = black outline
  2 = red mercury                3 = white fill (glass)

Mac 8-bit palette indices (validated set): white=0x00, black=0xFF,
pure red 0xFF0000 = 0x23 (6x6x6 cube: r0*36 + g5*6 + b5 = 35).
"""
import sys
from pathlib import Path

WHITE8, BLACK8, RED8 = 0x00, 0xFF, 0x23


def draw(W, H, cx, bulb_cy, bulb_r, tube_l, tube_r, tube_top, fill_from):
    """Return a WxH grid of codes for a vertical thermometer."""
    # solid = union of bulb disk and tube rectangle (inclusive)
    solid = [[False] * W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            in_bulb = (x - cx) ** 2 + (y - bulb_cy) ** 2 <= bulb_r ** 2
            in_tube = (tube_l <= x <= tube_r) and (tube_top <= y <= bulb_cy)
            solid[y][x] = in_bulb or in_tube

    def is_solid(x, y):
        return 0 <= x < W and 0 <= y < H and solid[y][x]

    grid = [[0] * W for _ in range(H)]
    for y in range(H):
        for x in range(W):
            if not solid[y][x]:
                continue
            # outline = solid pixel touching a non-solid neighbour (4-conn + edge)
            edge = (not is_solid(x - 1, y) or not is_solid(x + 1, y) or
                    not is_solid(x, y - 1) or not is_solid(x, y + 1))
            if edge:
                grid[y][x] = 1
            else:
                in_bulb = (x - cx) ** 2 + (y - bulb_cy) ** 2 <= bulb_r ** 2
                grid[y][x] = 2 if (in_bulb or y >= fill_from) else 3
    return grid


def pack_1bit(grid, predicate):
    """Pack a grid into MSB-first 1-bit rows; predicate(code)->bit."""
    H = len(grid); W = len(grid[0]); out = bytearray()
    rowbytes = (W + 7) // 8
    for y in range(H):
        row = bytearray(rowbytes)
        for x in range(W):
            if predicate(grid[y][x]):
                row[x >> 3] |= 0x80 >> (x & 7)
        out += row
    return out


def pack_8bit(grid):
    lut = {0: WHITE8, 1: BLACK8, 2: RED8, 3: WHITE8}
    out = bytearray()
    for row in grid:
        for c in row:
            out.append(lut[c])
    return out


def hexblock(data, indent="    "):
    lines = []
    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        lines.append(indent + '$"' + chunk.hex().upper() + '"')
    return "\n".join(lines)


def data_res(kind, rid, payload):
    return "data '%s' (%d) {\n%s\n};\n\n" % (kind, rid, hexblock(payload))


def main():
    out = Path(sys.argv[1] if len(sys.argv) > 1 else "therm_icon.r")

    big = draw(32, 32, cx=15, bulb_cy=25, bulb_r=6,
               tube_l=13, tube_r=18, tube_top=3, fill_from=16)
    small = draw(16, 16, cx=7, bulb_cy=12, bulb_r=3,
                 tube_l=6, tube_r=9, tube_top=1, fill_from=8)

    black_or_red = lambda c: c in (1, 2)
    opaque = lambda c: c != 0

    icn = pack_1bit(big, black_or_red) + pack_1bit(big, opaque)      # 128 + 128
    icl8 = pack_8bit(big)                                            # 1024
    ics = pack_1bit(small, black_or_red) + pack_1bit(small, opaque)  # 32 + 32
    ics8 = pack_8bit(small)                                          # 256

    assert len(icn) == 256 and len(icl8) == 1024
    assert len(ics) == 64 and len(ics8) == 256

    text = ("/* Thermometer Finder icon family for the CPU Temp CSM.\n"
            " * Generated by scripts/generate-icon.py -- do not hand-edit. */\n\n")
    text += data_res("ICN#", -16455, icn)
    text += data_res("icl8", -16455, icl8)
    text += data_res("ics#", -16455, ics)
    text += data_res("ics8", -16455, ics8)
    out.write_text(text)
    print("wrote %s (ICN#=%d icl8=%d ics#=%d ics8=%d)" %
          (out, len(icn), len(icl8), len(ics), len(ics8)))


if __name__ == "__main__":
    main()
